[tool.poetry]
name = "hbsir"
version = "0.4.1"
description = "An intuitive platform designed to simplify the analysis of Iran household budget survey data."
authors = ["mohammad amin alavian <m.amin.alavian@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"
bssir = "0.3.2"


[tool.poetry.group.dev.dependencies]
ipykernel = "*"
black = "*"
tabulate = "*"
mkdocs = "*"
mkdocs-material = "*"
mkdocs-literate-nav = "*"
mkdocs-autorefs = "*"
mkdocstrings-python = "*"
mkdocs-jupyter = "*"
pytest = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
