[project]
name = "hbsir"
version = "0.5.2"
description = "An intuitive platform designed to simplify the analysis of Iran household budget survey data."
readme = "README.md"
authors = [
  { name = "Mohammad Amin Alavian", email = "m.amin.alavian@gmail.com" }
]
license = { text = "MIT" }
keywords = ["iran", "survey", "data", "socioeconomic"]
requires-python = ">=3.10"
dependencies = [
    "bssir>=0.4.0"
]

[project.optional-dependencies]
dev = [
    "bssir[dev]>=0.4.0",
]

[project.urls]
Homepage = "https://github.com/Iran-Open-Data/HBSIR"
Repository = "https://github.com/Iran-Open-Data/HBSIR"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
hbsir = ["**/*.yaml"]
