# Package Name
package_name: HBSIR

# Local Directory
local_dir: Data/HBSIR
in_root: true

# Years (list of years or range in for of: "first_year - last_year")
years: "1363-1403"

# Local Settings
local_settings: config/hbsir_settings.yaml
